
server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://dpg-ctq01hggph6c73digek0-a.oregon-postgres.render.com:5432/ecommerce_xf71
    username: mimche
    password: miEykIRS90pK5kMTVHTNVUXx9VGfiFsP
    hikari:
      maximum-pool-size: 10   # Adjust the pool size according to your needs
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  main:
    web-application-type: servlet
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:./uploads/
  resources:
    add-mappings: false

  servlet:
    multipart:
      enabled: true                # Enable multipart file uploads
      max-file-size: 30MB          # Maximum size of an individual file
      max-request-size: 50MB       # Maximum size of a full request (including all files and form data)
      file-size-threshold: 2KB

logging:
  level:
    org.springframework.web: DEBUG